//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeniconHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incident()
        {
            this.document = new HashSet<document>();
            this.task = new HashSet<task>();
        }
    
        public int id_anomaly { get; set; }
        public string incident_code { get; set; }
        public string description { get; set; }
        public string lot_number { get; set; }
        public System.DateTime date_create { get; set; }
        public System.DateTime date_processing { get; set; }
        public System.DateTime date_update { get; set; }
        public System.DateTime date_close { get; set; }
        public int id_person { get; set; }
        public int id_type_anomaly { get; set; }
        public int id_statut { get; set; }
        public Nullable<int> id_engine { get; set; }
        public int id_area { get; set; }
        public Nullable<int> id_criticity { get; set; }
    
        public virtual area area { get; set; }
        public virtual criticity criticity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> document { get; set; }
        public virtual engine engine { get; set; }
        public virtual person person { get; set; }
        public virtual statut statut { get; set; }
        public virtual type_incident type_incident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> task { get; set; }
    }
}
