//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeniconHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeniconHelperEntities : DbContext
    {
        public MeniconHelperEntities()
            : base("name=MeniconHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<criticity> criticity { get; set; }
        public virtual DbSet<document> document { get; set; }
        public virtual DbSet<engine> engine { get; set; }
        public virtual DbSet<incident> incident { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<statut> statut { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<type_incident> type_incident { get; set; }
    }
}
